In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from rdkit import Chem

In [12]:
visco = pd.read_csv('data/Viscoelastic_WLM.csv')
visco.head()

,Source,ID_surfactant1,Type_surfactant1,SMILES_surfactant1,C_surfactant1 (mM),ID_surfactant2,Type_surfactant2,SMILES_surfactant2,C_surfactant2 (mM),ID_additive1,...,ID_additive2,SMILES_additive2,C_additive2 (mM),T [°C],Viscoelasticity,G₀ [Pa],"G""min [Pa]",ω* cr [rad/s],ͳR [s],η₀[Pa∙s]
0,A1,SLES,anionic,CCCCCCCCCCCCOCCOS(=O)(=O)[O-].[Na+],395.0,LED1A,zwitterionic,CCCCCCCCCCCC(=O)NCCCN+(C)C([O-])=O,55.0,NaCl,...,NaN,NaN,NaN,25,0.0,NaN,NaN,NaN,NaN,0.02
1,A1,SLES,anionic,CCCCCCCCCCCCOCCOS(=O)(=O)[O-].[Na+],395.0,LED1A,zwitterionic,CCCCCCCCCCCC(=O)NCCCN+(C)C([O-])=O,55.0,NaCl,...,NaN,NaN,NaN,25,1.0,4.0,2.70,150.0,0.01,0.03
2,A1,SLES,anionic,CCCCCCCCCCCCOCCOS(=O)(=O)[O-].[Na+],395.0,LED1A,zwitterionic,CCCCCCCCCCCC(=O)NCCCN+(C)C([O-])=O,55.0,NaCl,...,NaN,NaN,NaN,25,1.0,4.5,1.20,10.0,0.10,0.45
3,A1,SLES,anionic,CCCCCCCCCCCCOCCOS(=O)(=O)[O-].[Na+],395.0,LED1A,zwitterionic,CCCCCCCCCCCC(=O)NCCCN+(C)C([O-])=O,55.0,NaCl,...,NaN,NaN,NaN,25,1.0,5.0,0.50,0.8,1.25,6.25
4,A1,SLES,anionic,CCCCCCCCCCCCOCCOS(=O)(=O)[O-].[Na+],395.0,LED1A,zwitterionic,CCCCCCCCCCCC(=O)NCCCN+(C)C([O-])=O,55.0,NaCl,...,NaN,NaN,NaN,25,1.0,4.2,0.35,1.5,0.67,2.80

## Renaming columns

In [13]:
d = {
    'ID_surfactant1' : 'id_surfactant1',
    'Type_surfactant1' : 'type_surfactant1',
    'SMILES_surfactant1' : 'smiles_surfactant1',
    'C_surfactant1 (mM)' : 'c_surfactant1',
    'ID_surfactant2' : 'id_surfactant2',
    'Type_surfactant2' : 'type_surfactant2',
    'SMILES_surfactant2' : 'smiles_surfactant2',
    'C_surfactant2 (mM)' : 'c_surfactant2',
    'ID_additive1' : 'id_additive1',
    'SMILES_additive1' : 'smiles_additive1',
    'C_additive1 (mM)' : 'c_additive1',
    'ID_additive2' : 'id_additive2',
    'SMILES_additive2' : 'smiles_additive2',
    'C_additive2 (mM)' : 'c_additive2',
    'T [°C]' : 'temperature',
     'Viscoelasticity' : 'viscoelasticity',
    'G₀  [Pa]' : 'g_0',
    'G"min [Pa]' : 'g_min',
    'ω* cr [rad/s]' : 'omega_cr',
    'ͳR [s]' : 'tau_r',
    'η₀[Pa∙s]' : 'eta_0'
}

visco = visco.drop(columns=['Source'])
visco = visco.rename(columns = d)

## Replacing NaNs

In [14]:
visco = visco.dropna(subset=['viscoelasticity'])

In [15]:
visco[[
    'id_surfactant1',
    'type_surfactant1',
    'smiles_surfactant1',
    'id_surfactant2',
    'type_surfactant2',
    'smiles_surfactant2',
    'id_additive1',
    'smiles_additive1',
    'id_additive2',
    'smiles_additive2',
]] = \
visco[[
    'id_surfactant1',
    'type_surfactant1',
    'smiles_surfactant1',
    'id_surfactant2',
    'type_surfactant2',
    'smiles_surfactant2',
    'id_additive1',
    'smiles_additive1',
    'id_additive2',
    'smiles_additive2',
]].replace(np.nan, "None", regex=True)

In [16]:
visco[['c_surfactant1', 'c_surfactant2', 'c_additive1', 'c_additive2']] = visco[['c_surfactant1', 'c_surfactant2', 'c_additive1', 'c_additive2']].fillna(0)

In [17]:
visco.info()

<class 'pandas.DataFrame'>
Index: 8276 entries, 0 to 8394
Data columns (total 21 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   id_surfactant1      8276 non-null   str
 1   type_surfactant1    8276 non-null   str
 2   smiles_surfactant1  8276 non-null   str
 3   c_surfactant1       8276 non-null   float64
 4   id_surfactant2      8276 non-null   str
 5   type_surfactant2    8276 non-null   str
 6   smiles_surfactant2  8276 non-null   str
 7   c_surfactant2       8276 non-null   float64
 8   id_additive1        8276 non-null   str
 9   smiles_additive1    8276 non-null   str
 10  c_additive1         8276 non-null   float64
 11  id_additive2        8276 non-null   str
 12  smiles_additive2    8276 non-null   str
 13  c_additive2         8276 non-null   float64
 14  temperature         8276 non-null   int64
 15  viscoelasticity     8276 non-null   float64
 16  g_0                 5931 non-null   float64
 17  g_min               5928 non-null   float64
 18  omega_cr            5928 non-null   float64
 19  tau_r               5927 non-null   float64
 20  eta_0               8276 non-null   float64
dtypes: float64(10), int64(1), str(10)
memory usage: 1.4 MB

In [18]:
visco.head()

,id_surfactant1,type_surfactant1,smiles_surfactant1,c_surfactant1,id_surfactant2,type_surfactant2,smiles_surfactant2,c_surfactant2,id_additive1,smiles_additive1,...,id_additive2,smiles_additive2,c_additive2,temperature,viscoelasticity,g_0,g_min,omega_cr,tau_r,eta_0
0,SLES,anionic,CCCCCCCCCCCCOCCOS(=O)(=O)[O-].[Na+],395.0,LED1A,zwitterionic,CCCCCCCCCCCC(=O)NCCCN+(C)C([O-])=O,55.0,NaCl,[Na+].[Cl-],...,None,None,0.0,25,0.0,NaN,NaN,NaN,NaN,0.02
1,SLES,anionic,CCCCCCCCCCCCOCCOS(=O)(=O)[O-].[Na+],395.0,LED1A,zwitterionic,CCCCCCCCCCCC(=O)NCCCN+(C)C([O-])=O,55.0,NaCl,[Na+].[Cl-],...,None,None,0.0,25,1.0,4.0,2.70,150.0,0.01,0.03
2,SLES,anionic,CCCCCCCCCCCCOCCOS(=O)(=O)[O-].[Na+],395.0,LED1A,zwitterionic,CCCCCCCCCCCC(=O)NCCCN+(C)C([O-])=O,55.0,NaCl,[Na+].[Cl-],...,None,None,0.0,25,1.0,4.5,1.20,10.0,0.10,0.45
3,SLES,anionic,CCCCCCCCCCCCOCCOS(=O)(=O)[O-].[Na+],395.0,LED1A,zwitterionic,CCCCCCCCCCCC(=O)NCCCN+(C)C([O-])=O,55.0,NaCl,[Na+].[Cl-],...,None,None,0.0,25,1.0,5.0,0.50,0.8,1.25,6.25
4,SLES,anionic,CCCCCCCCCCCCOCCOS(=O)(=O)[O-].[Na+],395.0,LED1A,zwitterionic,CCCCCCCCCCCC(=O)NCCCN+(C)C([O-])=O,55.0,NaCl,[Na+].[Cl-],...,None,None,0.0,25,1.0,4.2,0.35,1.5,0.67,2.80

## Correcting SMILES typos

In [19]:
def validate_smiles(smiles):
    if smiles == 'None':
        return True
    mol = Chem.MolFromSmiles(str(smiles))
    if mol is None:
        return False
    return True

def correct_smiles(smiles):
    if smiles == 'CCCCCCCCCCCCCCCCOCC(O)CN+(C)C.[Br-]':
        return 'CCCCCCCCCCCCCCCCOCC(O)C[N+](C)C.[Br-]'
    elif smiles == 'CCCCCCCCCCCCCCCCN+(C)C.[Cl-]':
        return 'CCCCCCCCCCCCCCCC[N+](C)C.[Cl-]'
    elif smiles == 'CCCCCCCCCCCCCCCCN+(C)C.[Br-]':
        return 'CCCCCCCCCCCCCCCC[N+](C)C.[Br-]'
    elif smiles == 'CCCCCCCCCCCC(=O)NCCCN+(C)C([O-])=O':
        return 'CCCCCCCCCCCC(=O)NCCC[N+](C)C([O-])=O'
    elif smiles == 'CCCCCCCCCCCC(=O)NCCCN+(C)(C)CC([O-])=O':
        return 'CCCCCCCCCCCC(=O)NCCC[N+](C)(C)CC([O-])=O'
    elif smiles == '[Al+3].[O-]N+[O-].[O-]N+[O-].[O-]N+[O-]':
        return '[Al+3].[O-][N+][O-].[O-][N+][O-].[O-][N+][O-]'
    elif smiles == '[Na+].[O-]N+[O-]':
        return '[Na+].[O-][N+][O-]'
    elif smiles == 'CCCCCC1C(CCCCCC(=O)NCCCN(C)(C)CC(=O)[O-])C(C=CC1CCCCCC)CCCCCC(=O)NCCCN(C)(C)CC(=O)[O-]':
        return 'CCCCCCCCCCCC[N+](C)(C)CC(=O)[O-]'
    return smiles

In [20]:
visco['smiles_surfactant1'] = visco['smiles_surfactant1'].apply(correct_smiles)
visco['smiles_surfactant2'] = visco['smiles_surfactant2'].apply(correct_smiles)
visco['smiles_additive1'] = visco['smiles_additive1'].apply(correct_smiles)
visco['smiles_additive2'] = visco['smiles_additive2'].apply(correct_smiles)

In [21]:
smiles = list(visco['smiles_surfactant1'].unique())
smiles.extend(visco['smiles_surfactant2'].unique())
smiles.extend(visco['smiles_additive1'].unique())
smiles.extend(visco['smiles_additive2'].unique())
len(smiles)
for smile in smiles:
    if not validate_smiles(smile):
        print(smile)

In [22]:
visco.info()

<class 'pandas.DataFrame'>
Index: 8276 entries, 0 to 8394
Data columns (total 21 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   id_surfactant1      8276 non-null   str
 1   type_surfactant1    8276 non-null   str
 2   smiles_surfactant1  8276 non-null   str
 3   c_surfactant1       8276 non-null   float64
 4   id_surfactant2      8276 non-null   str
 5   type_surfactant2    8276 non-null   str
 6   smiles_surfactant2  8276 non-null   str
 7   c_surfactant2       8276 non-null   float64
 8   id_additive1        8276 non-null   str
 9   smiles_additive1    8276 non-null   str
 10  c_additive1         8276 non-null   float64
 11  id_additive2        8276 non-null   str
 12  smiles_additive2    8276 non-null   str
 13  c_additive2         8276 non-null   float64
 14  temperature         8276 non-null   int64
 15  viscoelasticity     8276 non-null   float64
 16  g_0                 5931 non-null   float64
 17  g_min               5928 non-null   float64
 18  omega_cr            5928 non-null   float64
 19  tau_r               5927 non-null   float64
 20  eta_0               8276 non-null   float64
dtypes: float64(10), int64(1), str(10)
memory usage: 1.4 MB

## SMILES to canonical

In [23]:
def smiles_to_canonical(smiles):
    if smiles == 'None':
        return smiles
    return Chem.MolToSmiles(Chem.MolFromSmiles(smiles))

In [24]:
columns = ['smiles_surfactant1', 'smiles_surfactant2','smiles_additive1', 'smiles_additive2']
visco[columns] = visco[columns].apply(lambda col: col.map(smiles_to_canonical))

In [25]:
visco.duplicated().sum()

np.int64(124)

In [26]:
visco = visco.drop_duplicates()

In [27]:
visco.to_csv('data/viscoelastic_cleared.csv', index=False)